In [63]:
# Importing pandas and numpy
import pandas as pd
import numpy as np


known_positive_1 = {'size': 'huge', 'color': 'black', 'covering': 'fur', 'foot-type': 'paw', 'leg-count': 2, 'arm-count': 4, 'eye-count': 2, 'horn-count': 0, 'lays-eggs': True, 'has-wings': True, 'has-gills': True, 'has-tail': True}
known_positive_2 = {'size': 'large', 'color': 'white', 'covering': 'fur', 'foot-type': 'paw', 'leg-count': 2, 'arm-count': 4, 'eye-count': 2, 'horn-count': 0, 'lays-eggs': True, 'has-wings': True, 'has-gills': True, 'has-tail': False}
known_positive_3 = {'size': 'huge', 'color': 'white', 'covering': 'fur', 'foot-type': 'paw', 'leg-count': 2, 'arm-count': 4, 'eye-count': 2, 'horn-count': 0, 'lays-eggs': True, 'has-wings': True, 'has-gills': False, 'has-tail': True}
known_positive_4 = {'size': 'large', 'color': 'black', 'covering': 'fur', 'foot-type': 'paw', 'leg-count': 1, 'arm-count': 3, 'eye-count': 2, 'horn-count': 0, 'lays-eggs': True, 'has-wings': True, 'has-gills': True, 'has-tail': True}
known_positive_5 = {'size': 'large', 'color': 'white', 'covering': 'fur', 'foot-type': 'foot', 'leg-count': 2, 'arm-count': 4, 'eye-count': 2, 'horn-count': 0, 'lays-eggs': True, 'has-wings': True, 'has-gills': False, 'has-tail': False}
known_negative_1 = {'size': 'large', 'color': 'blue', 'covering': 'fur', 'foot-type': 'paw', 'leg-count': 2, 'arm-count': 4, 'eye-count': 2, 'horn-count': 0, 'lays-eggs': True, 'has-wings': True, 'has-gills': True, 'has-tail': True}
known_negative_2 = {'size': 'tiny', 'color': 'red', 'covering': 'scales', 'foot-type': 'none', 'leg-count': 0, 'arm-count': 8, 'eye-count': 8, 'horn-count': 2, 'lays-eggs': False, 'has-wings': False, 'has-gills': False, 'has-tail': False}
known_negative_3 = {'size': 'medium', 'color': 'gray', 'covering': 'fur', 'foot-type': 'foot', 'leg-count': 2, 'arm-count': 6, 'eye-count': 2, 'horn-count': 0, 'lays-eggs': True, 'has-wings': False, 'has-gills': False, 'has-tail': False}
known_negative_4 = {'size': 'huge', 'color': 'black', 'covering': 'fur', 'foot-type': 'paw', 'leg-count': 2, 'arm-count': 6, 'eye-count': 2, 'horn-count': 2, 'lays-eggs': True, 'has-wings': True, 'has-gills': False, 'has-tail': False}
known_negative_5 = {'size': 'medium', 'color': 'purple', 'covering': 'fur', 'foot-type': 'talon', 'leg-count': 2, 'arm-count': 4, 'eye-count': 2, 'horn-count': 0, 'lays-eggs': False, 'has-wings': False, 'has-gills': True, 'has-tail': False}

monster_list = [(known_positive_1, True), (known_positive_2, True), (known_positive_3, True), (known_positive_4, True), (known_positive_5, True),
            (known_negative_1, False), (known_negative_2, False), (known_negative_3, False), (known_negative_4, False), (known_negative_5, False)]

new_monster_1 = {'size': 'large', 'color': 'black', 'covering': 'fur', 'foot-type': 'paw', 'leg-count': 1, 'arm-count': 3, 'eye-count': 2, 'horn-count': 0, 'lays-eggs': True, 'has-wings': True, 'has-gills': True, 'has-tail': True}
new_monster_2 = {'size': 'tiny', 'color': 'red', 'covering': 'scales', 'foot-type': 'none', 'leg-count': 0, 'arm-count': 8, 'eye-count': 8, 'horn-count': 2, 'lays-eggs': False, 'has-wings': False, 'has-gills': False, 'has-tail': False}
new_monster_3 = {'size': 'large', 'color': 'gray', 'covering': 'fur', 'foot-type': 'foot', 'leg-count': 1, 'arm-count': 3, 'eye-count': 2, 'horn-count': 0, 'lays-eggs': True, 'has-wings': True, 'has-gills': False, 'has-tail': False}
new_monster_4 = {'size': 'small', 'color': 'black', 'covering': 'scales', 'foot-type': 'paw', 'leg-count': 2, 'arm-count': 4, 'eye-count': 2, 'horn-count': 0, 'lays-eggs': True, 'has-wings': True, 'has-gills': False, 'has-tail': False}

# # Reading the csv file into a pandas DataFrame
# data = pd.read_csv('student_data.csv')

# # Printing out the first 10 rows of our data
# data[:10]

In [64]:
# def transform(monster):
#     for a in ['black', 'white', 'brown', 'gray', 'red', 'yellow', 'blue', 'green', 'orange', 'purple']:
#         if (monster['color']==a):
#             monster['color'+'-'+a]=1
#             break
#         elif(a=='purple'):
#             monster['color'+'-'+a]=0
#             monster.drop("color")
#             break
#         else:
#             monster['color'+'-'+a]=0
#     for b in ['tiny', 'small', 'medium', 'large', 'huge']:
#         if (monster['size']==b):
#             monster['size'+'-'+b]=1
#             break
#         elif(b=='huge'):
#             monster['size'+''+b]=0
#             monster.drop("size")
#             break
#         else:
#             monster['size'+''+b]=0
#     for c in [ 'fur', 'feathers', 'scales', 'skin']:
#         if (monster['covering']==c):
#             monster['covering'+'-'+c]=1
#             break
#         elif(c=='skin'):
#             monster['covering'+'-'+c]=0
#             monster.drop('covering') 
#             break
#         else:
#             monster['covering'+'-'+c]=0
#     for d in ['paw', 'hoof', 'talon', 'foot', 'none']:
#         if (monster['foot-type']==d):
#             monster['foot-type'+'-'+d]=1
#             break
#         elif(d=='none'):
#             monster['foot-type'+'-'+d]=0
#             monster.drop("foot-type")
#             break
#         else:
#             monster['foot-type'+'-'+d]=0
    
#     return monster

In [65]:
# monsterdf=[]
# for a in monster_list:
#     a[0]['is_monster']=a[1]
#     b =transform(a[0])
#     monsterdf.append(b)
# # monsterdf.append(new_monster_1) 
# data= pd. DataFrame(monsterdf)
# data

In [66]:
monsterdf=[]
for a in monster_list:
    a[0]['is_monster']=a[1]
    monsterdf.append(a[0])
data= pd. DataFrame(monsterdf)

In [67]:
m1=pd.DataFrame([new_monster_1])

In [68]:
one_hot_data = pd.get_dummies(data, columns=['size',  'color', 'covering' ,'foot-type'  ,  'lays-eggs' , 'has-wings' , 'has-gills' , 'has-tail' ],)
one_hot_m1 = pd.get_dummies(m1, columns=['size',  'color', 'covering' ,'foot-type' ,  'lays-eggs' , 'has-wings' , 'has-gills' , 'has-tail' ])

In [69]:
one_hot_m1

,leg-count,arm-count,eye-count,horn-count,size_large,color_black,covering_fur,foot-type_paw,lays-eggs_True,has-wings_True,has-gills_True,has-tail_True
0,1,3,2,0,1,1,1,1,1,1,1,1

In [70]:
a= (one_hot_data.keys())
c= (one_hot_m1.keys())
new_list = list(set(a).difference(c))
for q in new_list:
    one_hot_m1[q]=0
for b in new_list:
    print(b)
print(len(a)-len(c))
d=(one_hot_m1.keys())
print(len(a)-len(d))
print(new_list)
one_hot_m1

has-gills_False
size_tiny
color_gray
color_white
size_medium
covering_scales
foot-type_foot
lays-eggs_False
color_red
is_monster
has-wings_False
foot-type_none
has-tail_False
color_purple
color_blue
foot-type_talon
size_huge
17
0
['has-gills_False', 'size_tiny', 'color_gray', 'color_white', 'size_medium', 'covering_scales', 'foot-type_foot', 'lays-eggs_False', 'color_red', 'is_monster', 'has-wings_False', 'foot-type_none', 'has-tail_False', 'color_purple', 'color_blue', 'foot-type_talon', 'size_huge']

,leg-count,arm-count,eye-count,horn-count,size_large,color_black,covering_fur,foot-type_paw,lays-eggs_True,has-wings_True,...,lays-eggs_False,color_red,is_monster,has-wings_False,foot-type_none,has-tail_False,color_purple,color_blue,foot-type_talon,size_huge
0,1,3,2,0,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0

In [71]:
one_hot_data

,leg-count,arm-count,eye-count,horn-count,is_monster,size_huge,size_large,size_medium,size_tiny,color_black,...,foot-type_paw,foot-type_talon,lays-eggs_False,lays-eggs_True,has-wings_False,has-wings_True,has-gills_False,has-gills_True,has-tail_False,has-tail_True
0,2,4,2,0,True,1,0,0,0,1,...,1,0,0,1,0,1,0,1,0,1
1,2,4,2,0,True,0,1,0,0,0,...,1,0,0,1,0,1,0,1,1,0
2,2,4,2,0,True,1,0,0,0,0,...,1,0,0,1,0,1,1,0,0,1
3,1,3,2,0,True,0,1,0,0,1,...,1,0,0,1,0,1,0,1,0,1
4,2,4,2,0,True,0,1,0,0,0,...,0,0,0,1,0,1,1,0,1,0
5,2,4,2,0,False,0,1,0,0,0,...,1,0,0,1,0,1,0,1,0,1
6,0,8,8,2,False,0,0,0,1,0,...,0,0,1,0,1,0,1,0,1,0
7,2,6,2,0,False,0,0,1,0,0,...,0,0,0,1,1,0,1,0,1,0
8,2,6,2,2,False,1,0,0,0,1,...,1,0,0,1,0,1,1,0,1,0
9,2,4,2,0,False,0,0,1,0,0,...,0,1,1,0,1,0,0,1,1,0

In [72]:
one_hot_data
def find_mean_and_std(data,data2):
    meand=[]
    stdd=[]
    for field in ['arm-count', 'eye-count','horn-count','leg-count']:
        mean, std = data[field].mean(), data[field].std()
        meand.append({
        field:mean})
        stdd.append({
        field:mean})
        data.loc[:,field] = (data[field]-mean)/std
        data2.loc[:,field] = (data2[field]-mean)/std
    return meand,stdd

mean,sted= find_mean_and_std(one_hot_data,one_hot_m1) 

one_hot_data

,leg-count,arm-count,eye-count,horn-count,is_monster,size_huge,size_large,size_medium,size_tiny,color_black,...,foot-type_paw,foot-type_talon,lays-eggs_False,lays-eggs_True,has-wings_False,has-wings_True,has-gills_False,has-gills_True,has-tail_False,has-tail_True
0,0.444478,-0.468405,-0.316228,-0.474342,True,1,0,0,0,1,...,1,0,0,1,0,1,0,1,0,1
1,0.444478,-0.468405,-0.316228,-0.474342,True,0,1,0,0,0,...,1,0,0,1,0,1,0,1,1,0
2,0.444478,-0.468405,-0.316228,-0.474342,True,1,0,0,0,0,...,1,0,0,1,0,1,1,0,0,1
3,-1.037116,-1.137554,-0.316228,-0.474342,True,0,1,0,0,1,...,1,0,0,1,0,1,0,1,0,1
4,0.444478,-0.468405,-0.316228,-0.474342,True,0,1,0,0,0,...,0,0,0,1,0,1,1,0,1,0
5,0.444478,-0.468405,-0.316228,-0.474342,False,0,1,0,0,0,...,1,0,0,1,0,1,0,1,0,1
6,-2.518710,2.208194,2.846050,1.897367,False,0,0,0,1,0,...,0,0,1,0,1,0,1,0,1,0
7,0.444478,0.869894,-0.316228,-0.474342,False,0,0,1,0,0,...,0,0,0,1,1,0,1,0,1,0
8,0.444478,0.869894,-0.316228,1.897367,False,1,0,0,0,1,...,1,0,0,1,0,1,1,0,1,0
9,0.444478,-0.468405,-0.316228,-0.474342,False,0,0,1,0,0,...,0,1,1,0,1,0,0,1,1,0

In [73]:
mean

[{'arm-count': 4.7},
 {'eye-count': 2.6},
 {'horn-count': 0.4},
 {'leg-count': 1.7}]

In [74]:
one_hot_m1

,leg-count,arm-count,eye-count,horn-count,size_large,color_black,covering_fur,foot-type_paw,lays-eggs_True,has-wings_True,...,lays-eggs_False,color_red,is_monster,has-wings_False,foot-type_none,has-tail_False,color_purple,color_blue,foot-type_talon,size_huge
0,-1.037116,-1.137554,-0.316228,-0.474342,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0

In [75]:
# last= one_hot_data.drop(one_hot_data.tail(n).index,inplace=True) 
DFT = one_hot_data[:-1]
# DFT["is_monster"] = DFT["is_monster"].astype(int)
DFT

,leg-count,arm-count,eye-count,horn-count,is_monster,size_huge,size_large,size_medium,size_tiny,color_black,...,foot-type_paw,foot-type_talon,lays-eggs_False,lays-eggs_True,has-wings_False,has-wings_True,has-gills_False,has-gills_True,has-tail_False,has-tail_True
0,0.444478,-0.468405,-0.316228,-0.474342,True,1,0,0,0,1,...,1,0,0,1,0,1,0,1,0,1
1,0.444478,-0.468405,-0.316228,-0.474342,True,0,1,0,0,0,...,1,0,0,1,0,1,0,1,1,0
2,0.444478,-0.468405,-0.316228,-0.474342,True,1,0,0,0,0,...,1,0,0,1,0,1,1,0,0,1
3,-1.037116,-1.137554,-0.316228,-0.474342,True,0,1,0,0,1,...,1,0,0,1,0,1,0,1,0,1
4,0.444478,-0.468405,-0.316228,-0.474342,True,0,1,0,0,0,...,0,0,0,1,0,1,1,0,1,0
5,0.444478,-0.468405,-0.316228,-0.474342,False,0,1,0,0,0,...,1,0,0,1,0,1,0,1,0,1
6,-2.518710,2.208194,2.846050,1.897367,False,0,0,0,1,0,...,0,0,1,0,1,0,1,0,1,0
7,0.444478,0.869894,-0.316228,-0.474342,False,0,0,1,0,0,...,0,0,0,1,1,0,1,0,1,0
8,0.444478,0.869894,-0.316228,1.897367,False,1,0,0,0,1,...,1,0,0,1,0,1,1,0,1,0

In [76]:
features = one_hot_data.drop('is_monster', axis=1)
targets = one_hot_data['is_monster']
test_features = one_hot_m1.drop('is_monster', axis=1)

In [77]:
test_features

,leg-count,arm-count,eye-count,horn-count,size_large,color_black,covering_fur,foot-type_paw,lays-eggs_True,has-wings_True,...,foot-type_foot,lays-eggs_False,color_red,has-wings_False,foot-type_none,has-tail_False,color_purple,color_blue,foot-type_talon,size_huge
0,-1.037116,-1.137554,-0.316228,-0.474342,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0

In [78]:
# Activation (sigmoid) function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
def sigmoid_prime(x):
    return sigmoid(x) * (1-sigmoid(x))
def error_formula(y, output):
    return - y*np.log(output) - (1 - y) * np.log(1-output)

In [79]:
## Alternative solution ##
# you could also *only* use y and the output 
# and calculate sigmoid_prime directly from the activated output!

# below is an equally valid solution (it doesn't utilize x)
def error_term_formula(x, y, output):
    return (y-output) * output * (1 - output)

In [80]:
# Neural Network hyperparameters
epochs = 1000
learnrate = 0.5

# Training function
def train_nn(features, targets, epochs, learnrate):
    
    # Use to same seed to make debugging easier
    np.random.seed(42)

    n_records, n_features = features.shape
    last_loss = None

    # Initialize weights
    weights = np.random.normal(scale=1 / n_features**.5, size=n_features)

    for e in range(epochs):
        del_w = np.zeros(weights.shape)
        for x, y in zip(features.values, targets):
            # Loop through all records, x is the input, y is the target

            # Activation of the output unit
            #   Notice we multiply the inputs and the weights here 
            #   rather than storing h as a separate variable 
            output = sigmoid(np.dot(x, weights))

            # The error, the target minus the network output
            error = error_formula(y, output)

            # The error term
            error_term = error_term_formula(x, y, output)

            # The gradient descent step, the error times the gradient times the inputs
            del_w += error_term * x

        # Update the weights here. The learning rate times the 
        # change in weights, divided by the number of records to average
        weights += learnrate * del_w / n_records

        # Printing out the mean square error on the training set
        if e % (epochs / 10) == 0:
            out = sigmoid(np.dot(features, weights))
            loss = np.mean((out - targets) ** 2)
#             print("Epoch:", e)
#             if last_loss and last_loss < loss:
#                 print("Train loss: ", loss, "  WARNING - Loss Increasing")
#             else:
#                 print("Train loss: ", loss)
            last_loss = loss
#             print("=========")
#     print("Finished training!")
    return weights
    
weights = train_nn(features, targets, epochs, learnrate)

In [81]:
targets

0     True
1     True
2     True
3     True
4     True
5    False
6    False
7    False
8    False
9    False
Name: is_monster, dtype: bool

In [83]:
# Calculate accuracy on test data
test_out = sigmoid(np.dot(features, weights))
predictions = test_out > 0.5
accuracy = np.mean(predictions == targets)
print("Prediction accuracy: {:.3f}".format(accuracy))
print(predictions)

Prediction accuracy: 1.000
[ True  True  True  True  True False False False False False]